spring:
  output:
    ansi:
      enabled: always
  r2dbc:
    url: 'r2dbc:h2:mem:///h2database'
    username: 'h2user'
    password: 'h2password'
    properties:
      Mode: PostgreSQL
      MULTI_THREADED: TRUE
      DB_CLOSE_ON_EXIT: FALSE
  liquibase:
    change-log: classpath*:/liquibase/changelog-master.xml
    liquibase-schema: PUBLIC
    default-schema: PUBLIC
server:
  port: 8004
logging:
  level:
    io.netty.resolver.dns.DnsServerAddressStreamProviders: off
