spring:
  output:
    ansi:
      enabled: always
  r2dbc:
    url: 'r2dbc:mysql://127.0.0.1:3306/database'
    username: 'user'
    password: 'password'
  liquibase:
    change-log: classpath*:/liquibase/changelog-master.xml
server:
  port: 8080
logging:
  level:
    io.netty.resolver.dns.DnsServerAddressStreamProviders: off
