spring:
  output:
    ansi:
      enabled: always
  r2dbc:
    url: 'r2dbc:h2:file:///./target/h2database'
    username: 'h2user'
    password: 'h2password'
    properties:
      Mode: MySQL
      AUTO_SERVER: TRUE
      AUTO_RECONNECT: TRUE
      MULTI_THREADED: TRUE
      DB_CLOSE_ON_EXIT: TRUE
  liquibase:
    change-log: classpath*:/liquibase/changelog-master.xml
    liquibase-schema: PUBLIC
    default-schema: APP
server:
  port: 8003
logging:
  level:
    io.netty.resolver.dns.DnsServerAddressStreamProviders: off
