# Sample workflow for building and deploying a VuePress site to GitHub Pages
name: pages
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Go to Setting => Environments => Deployment branches: select All branches
  push:
    tags: [ '*' ]
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
# Use concrete NodeJS version:
env:
  NODE_VERSION: 18.4.0
jobs:
  # Build job:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - uses: actions/cache@v3
        id: ci
        with:
          path: |
            ~/.m2
            ~/.npm
            ~/.node
            ~/.docker
            ~/.gradle
            !~/.m2/repository/io/gituhb/daggerok
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/pom.xml', '**/package.json', '**/package-lock.json') }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm --prefix docs install -E
      - run: npm --prefix docs run pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs/.vuepress/dist'
  # Deployment job:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
