name: pages
# Runs on pushes targeting the default branch
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Go to Setting => Environments => Deployment branches: select All branches
  push: # branches: ["master"] # tags: [ '*' ] # lets deploy GitHub pages on every commit
# # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages to allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
env:
  NODE_VERSION: 19.7.0
jobs:
  # Build job:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Please verify that the repository has Pages enabled and configured to build using GitHub Actions
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - uses: actions/cache@v3
        id: ci
        with:
          path: |
            ~/.m2
            ~/.npm
            ~/.node
            ~/.docker
            ~/.gradle
            !~/.m2/repository/io/gituhb/daggerok
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/pom.xml', '**/package.json', '**/package-lock.json') }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm --prefix docs install -E
      - run: npm --prefix docs run pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs/.vuepress/dist'
  # Deployment job:
  deploy:
    # Add a dependency to the build job
    needs: build
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      # contents: read
      pages: write
      id-token: write
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action: https://github.com/actions/deploy-pages/releases
