name: tests
on:
  push:
    branches:
      - '*'
env:
  MYSQL_VERSION: '8.0.24'
jobs:
  tests:
    name: unit tests java-${{ matrix.java }}
    if: github.event.inputs.trigger == ''
      || !startsWith(github.event.inputs.trigger, 'm')
      || !startsWith(github.event.inputs.trigger, 'M')
    strategy:
      matrix:
        java: [11, 17, 18]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v2
        with:
          # 'temurin' 'zulu' 'adopt' 'adopt-hotspot' 'adopt-openj9' 'liberica' 'microsoft'
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.m2
            ~/.npm
            ~/.docker
            ~/.gradle
          key: ${{ runner.os }}-build-${{ hashFiles('**/*gradle*', '**/pom.xml', '**/package.json', '**/package-lock.json') }}
      - run: if [[ "" != `docker ps -aq` ]] ; then docker rm -f -v `docker ps -aq` ; fi
      - run: cd $GITHUB_WORKSPACE ; ./mvnw
  liquibase-r2dbc-spring-boot-starter-example:
    name: liquibase-r2dbc-spring-boot-starter-example integration tests java-${{ matrix.java }}
    if: github.event.inputs.trigger == ''
      || !startsWith(github.event.inputs.trigger, 'm')
      || !startsWith(github.event.inputs.trigger, 'M')
    strategy:
      matrix:
        java: [11, 17, 18]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.m2
            ~/.npm
            ~/.docker
            ~/.gradle
          key: ${{ runner.os }}-build-${{ hashFiles('**/*gradle*', '**/pom.xml', '**/package.json', '**/package-lock.json') }}
      - run: sudo apt install -y httpie
      - run: docker pull mysql:${{ env.MYSQL_VERSION }}
      - run: if [[ "" != `docker ps -aq` ]] ; then docker rm -f -v `docker ps -aq` ; fi
      - run: |
          docker run -d --rm --name mysql --platform=linux/x86_64 \
            --health-cmd='mysqladmin ping -h 127.0.0.1 -u $MYSQL_USER --password=$MYSQL_PASSWORD || exit 1' \
            --health-start-period=1s --health-retries=1111 --health-interval=1s --health-timeout=5s \
            -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=database \
            -e MYSQL_USER=user -e MYSQL_PASSWORD=password \
            -p 3306:3306 \
            mysql:8.0.24
      - run: while [[ $(docker ps -n 1 -q -f health=healthy -f status=running | wc -l) -lt 1 ]] ; do sleep 3 ; echo -n '.' ; done ; sleep 15; echo 'MySQL is ready.'
      - run: rm -rf ~/.m2/repository/daggerok//liquibase/r2dbc*
      - run: ./mvnw clean install -DskipTests
      - run: cd $GITHUB_WORKSPACE ; ./mvnw -f liquibase-r2dbc-spring-boot-starter-example spring-boot:start
      - run: http --ignore-stdin  get :8080
      - run: http --ignore-stdin  get :8080/api
      - run: http --ignore-stdin  get :8080/api/messages
      - run: http --ignore-stdin post :8080/api/messages body=hey
      - run: http --ignore-stdin  get :8080/api/messages
      - run: cd $GITHUB_WORKSPACE ; ./mvnw -f liquibase-r2dbc-spring-boot-starter-example spring-boot:stop
      - run: cd $GITHUB_WORKSPACE ; docker stop mysql
